.travis.yml
=> [config] Write travis.yml #6

readme.md
=> Add readme file #3

client/components/header/__snapshots__/header.test.js.snap, client/components/header/header.js, client/components/header/header.test.js, client/components/header/index.js, client/index.js, client/routes.js, client/store/index.js, config/jest.config.js
=> [tests] Setup Jest with Enzyme for testing react components #5

client/components/organization-wrapper/organization-wrapper.js, client/components/password-confirm/index.css, client/components/password-confirm/index.js, client/components/password-confirm/password-confirm.js, client/components/password-reset/index.css, client/components/password-reset/index.js, client/components/password-reset/password-reset.js, client/components/registration/registration.js, client/constants/index.js, org-configurations/default-configuration.yml
=> [component] Add Password reset component #17

client/components/organization-wrapper/organization-wrapper.js, client/components/password-change/index.css, client/components/password-change/index.js, client/components/password-change/password-change.js, client/components/status/__snapshots__/status.test.js.snap, client/components/status/index.css, client/components/status/status.js, client/constants/index.js, client/index.js, client/utils/history.js, org-configurations/default-configuration.yml, package-lock.json, package.json
Fixes #32 
Hey! This is v1 of the password change component, please have a look!
Here's what it looks like:
You can view it on the `/default/change-password` route.
Regards,
Somesh
=> [Fix #32] Finish the password change component

.eslintrc.json, .gitignore, client/components/login/login.js, client/components/login/login.test.js, client/components/password-change/password-change.js, client/components/password-confirm/password-confirm.js, client/components/password-confirm/password-confirm.test.js, client/components/password-reset/password-reset.js, client/components/password-reset/password-reset.test.js, client/components/registration/registration.js, client/components/registration/registration.test.js, client/components/status/status.js, client/components/status/status.test.js, client/constants/index.js, client/index.js, client/utils/get-error-text.js, client/utils/log-error.js, package-lock.json, package.json, server/controllers/obtain-token-controller.js, server/controllers/password-change-controller.js, server/controllers/password-reset-confirm-controller.js, server/controllers/password-reset-controller.js, server/controllers/registration-controller.js, server/controllers/validate-token-controller.js, server/utils/log-internal-error.js
This is a PR for commit which adds `react-toastify` library to make UX better. Changes:
- adds `react-toastify` in `package.json`
- Connects `react-toastify` in `login`, `password-confirm`, `password-reset`, `registration`, `status` pages:
- Updates tests to check if toast function calls and added console error existance check
- Updates `index.js` to add callback param to call function after redirect
- Updates main files to add toast function calls on `axios` response
- Adds new error and success messages to `client/constants/index.js`
- check my code-based review for notes
- feel free to ask for any changes
Fixes #40, fixes #45
=> [ux] User notification #40 #45

config/webpack.config.js, package-lock.json, package.json
PR for commit which adds compression-webpack-plugin to webpack.config.js
Feel free to comment, also I want to know if we should delete original assets (that's how it works now) or not
Closes #49
=> [config] add compression-webpack-plugin to webpack production config #49

client/actions/parse-organizations.js, client/index.js, client/routes.js, client/utils/sort-organizations.js, server/index.js
Add a Redirect route to route to the first organization found in alphabetical order if root url is accessed
closes #56
=> [component] add a Redirect Route #56

client/components/login/login.js, client/components/login/login.test.js, client/components/organization-wrapper/index.css, client/components/organization-wrapper/organization-wrapper.js, client/components/password-change/password-change.js, client/components/password-confirm/password-confirm.js, client/components/password-confirm/password-confirm.test.js, client/components/password-reset/password-reset.js, client/components/password-reset/password-reset.test.js, client/components/registration/registration.js, client/components/registration/registration.test.js, client/utils/loading-context.js
=> [UI] Add loading indicator

client/components/header/__snapshots__/header.test.js.snap, client/components/header/header.js, client/components/header/index.css, client/components/header/index.js, client/components/login/__snapshots__/login.test.js.snap, client/components/login/index.css, client/components/login/login.js, client/components/password-change/index.css, client/components/password-change/password-change.js, client/components/password-reset/__snapshots__/password-reset.test.js.snap, client/components/password-reset/index.css, client/components/password-reset/password-reset.js, client/components/registration/__snapshots__/registration.test.js.snap, client/components/registration/index.css, client/components/registration/registration.js, client/components/status/__snapshots__/status.test.js.snap, client/components/status/index.css, client/components/status/status.js, client/index.css
=> [components] make one css class for all buttons

server/controllers/password-change-controller.js
This adds support for https://github.com/openwisp/openwisp-radius/pull/139, @Vivekrajput20 do you know if there are other parts that need to be changed?
=> [change] Switch to Bearer token

client/index.css, config/webpack.config.js, package-lock.json, package.json
Configured file-loader withwebpack, added fonts to the application and changed index.css to remove blocking font #79
=> [bug] Fixed  blocking font in captive portal #79

client/components/contact-box/contact.js, client/components/contact-box/contact.test.js, client/components/contact-box/index.js, client/components/footer/__snapshots__/footer.test.js.snap, client/components/footer/footer.js, client/components/footer/footer.test.js, client/components/footer/index.js, client/components/header/__snapshots__/header.test.js.snap, client/components/header/header.js, client/components/header/header.test.js, client/components/status/index.js, client/components/status/status.js, client/components/status/status.test.js, client/utils/log-error.js, client/utils/should-link-be-shown.js, client/utils/utils.test.js, readme.md
=> [feature] Allow specifying if links should be shown to authenticated/unauthenticated users only #93

readme.md
=> [readme] Update readme #57

internals/generators/organization/config.yml.hbs, internals/generators/organization/index.js, readme.md
=> [feature] Added option to specify host url #102

client/components/mobile-phone-change/__snapshots__/mobile-phone-change.test.js.snap, client/components/mobile-phone-change/index.js, client/components/mobile-phone-change/mobile-phone-change.js, client/components/mobile-phone-change/mobile-phone-change.test.js, internals/generators/organization/config.yml.hbs
=> [feature] Active users can change phone number #106

client/components/mobile-phone-verification/mobile-phone-verification.js, server/controllers/mobile-phone-token-controller.js
=> [fix] Added phone_number to create phone token post #126

.eslintrc.json, client/components/status/__snapshots__/status.test.js.snap, client/components/status/status.js, client/components/status/status.test.js, client/index.css, client/test-config.json, internals/generators/organization/config.yml.hbs, org-configurations/default-configuration.yml
=> [feature] Added user info to status page #104

README.md, client/components/mobile-phone-change/__snapshots__/mobile-phone-change.test.js.snap, client/components/registration/registration.js, client/components/registration/registration.test.js, client/test-config.json, internals/generators/organization/config.yml.hbs, org-configurations/default-configuration.yml, server/controllers/registration-controller.js
=> [feature] Added more user fields #151

client/components/organization-wrapper/index.css, client/index.css, public/index.html
Added a custom loading animation which fixes #156
=> added a loading animation

README.md
Added Configure social login section fixes #185
=> [Docs] social login config #185

config/webpack.config.js, package.json
Reduces build size from 269kb to 267kb
Related to #167
=> [wifi-login-pages] Used terser-plugin to reduce js file size #167

yarn.lock
Closes #125 
After updating dependency packages in yarn.lock file. Now all tests are passed.
@Purhan @nemesisdesign please review this PR.
=> [deps] Update history #125

client/components/login/__snapshots__/login.test.js.snap, client/components/login/index.css, client/components/login/login.js, client/components/login/login.test.js, client/components/mobile-phone-change/mobile-phone-change.js, client/components/mobile-phone-verification/mobile-phone-verification.js, client/components/password-change/index.js, client/components/password-change/password-change.js, client/components/password-change/password-change.test.js, client/components/status/status.js, client/utils/authenticate.js, client/utils/session.js, internals/generators/organization/config.yml.hbs, internals/generators/organization/index.js, org-configurations/default-configuration.yml, package.json, server/controllers/mobile-phone-number-change-controller.js, server/controllers/mobile-phone-token-controller.js, server/controllers/obtain-token-controller.js, server/controllers/password-change-controller.js, server/controllers/user-radius-sessions-controller.js, server/controllers/validate-token-controller.js, yarn.lock
Added remember_me checkbox with sessionStorage.
Closes #63
=> [wifi-login-pages] Added remember me checkbox #63

.github/dependabot.yml, .gitignore, .prettierignore, client/components/login/__snapshots__/login.test.js.snap, client/components/login/index.css, client/components/login/login.js, internals/generators/organization/config.yml.hbs, org-configurations/default-configuration.yml, public/index.html, yarn.lock
=> [chores] Minor improvements

client/components/status/status.js
The O character is due to the boolean in spinner.
Used ternary operator to fix this.
Fixes #218
=> [Fix] Removed strange O character in status page #218

README.md, client/components/login/__snapshots__/login.test.js.snap, client/components/login/login.js, client/components/login/login.test.js, internals/generators/organization/config.yml.hbs, org-configurations/default-configuration.yml
=> [feature] Allow forcing text input for username field in login form #89

client/components/mobile-phone-change/mobile-phone-change.js
=> [fix] Change phone number invalid token fixed

client/utils/session.js
=> [chore] Add comments in handleSession utils function

server/controllers/registration-controller.js
Depends on https://github.com/openwisp/openwisp-radius/pull/258.
=> [change] Updated to the latest openwisp-radius code

client/components/login/login.js, client/components/login/login.test.js
=> [Fix] Changed toast for login error when connection refused

README.md, client/components/status/status.js, client/components/status/status.test.js, internals/generators/organization/index.js, org-configurations/default-configuration.yml
=> [tests] Mocks support added for captive portal login and logout

client/actions/actions.test.js, client/actions/set-organization.js, client/components/organization-wrapper/organization-wrapper.js, client/components/status/status.test.js, client/reducers/organization.js, client/reducers/reducers.test.js
=> [fix] Changed is_verified to default to null #270

client/components/organization-wrapper/organization-wrapper.test.js
I added these tests yesterday because I needed to add a test for ensuring credit card verification is initiated, and that's when I come to the conclusions explained in https://github.com/openwisp/openwisp-wifi-login-pages/issues/272, so I ended up moving the logic which initiates the credit card verification in the status component and moved the test there as well (I think we should concentrate the logic which initiates identity verification in the status component and have all other modules simply redirect to status to initiate verification, it's a lot simpler).
However, I did quite some work to figure out how to test the behavior of routes so I don't want to throw this away because we have basically no tests for routes and we should have more.
=> [tests] Added basic tests for status route

README.md, client/components/contact-box/contact.js, client/components/contact-box/contact.test.js, client/components/contact-box/index.js, client/components/footer/footer.js, client/components/footer/footer.test.js, client/components/footer/index.js, client/components/header/header.js, client/components/header/header.test.js, client/components/header/index.js, client/components/mobile-phone-change/__snapshots__/mobile-phone-change.test.js.snap, client/components/organization-wrapper/organization-wrapper.test.js, client/components/status/status.js, client/utils/should-link-be-shown.js, client/utils/utils.test.js, internals/generators/organization/config.yml.hbs, org-configurations/default-configuration.yml
Passed userData in shouldLinkBeShown to handle links for verified users.
Closes #107
=> [feature] Allow specifying if link should be shown to verified users #107

.github/workflows/ci.yml, README.md, browser-test/clear_data.py, browser-test/initialize_data.py, browser-test/login.test.js, browser-test/registration.test.js, browser-test/testData.json, browser-test/utils.js, client/components/organization-wrapper/organization-wrapper.test.js, package.json, yarn.lock
=> [feature] Added selenium tests for login and signup

.eslintrc.json, browser-test/clear_data.py, browser-test/login.test.js, browser-test/registration.test.js, browser-test/utils.js
=> [tests] Fixed browser tests #280

browser-test/login.test.js, browser-test/registration.test.js, browser-test/utils.js
@codesankalp let's avoid to leave unused code ok?
=> [tests] Further improvements to browser tests

client/components/logout/__snapshots__/logout.test.js.snap, client/components/logout/index.js, client/components/logout/logout.js, client/components/logout/logout.test.js
Captive portal login was not being performed when clicking on "log me in again" from logout component.
I added a failing test which fails without the fix.
=> [fix] Perform captive portal login on "log me in again"

client/components/payment-status/__snapshots__/payment-status.test.js.snap, client/components/payment-status/payment-status.js, client/components/payment-status/payment-status.test.js, client/components/status/status.js, client/components/status/status.test.js
Various improvements to credit card verification flow.
=> [change] Improved credit card verification flow

client/components/login/__snapshots__/login.test.js.snap, client/components/login/login.js, client/components/password-change/__snapshots__/password-change.test.js.snap, client/components/password-change/password-change.js, client/components/password-confirm/__snapshots__/password-confirm.test.js.snap, client/components/password-confirm/password-confirm.js, client/components/password-reset/__snapshots__/password-reset.test.js.snap, client/components/password-reset/password-reset.js, client/components/registration/__snapshots__/registration.test.js.snap, client/components/registration/registration.js
=> [chores] Added explicit autocomplete attribute to input fields #275

client/components/contact-box/__snapshots__/contact.test.js.snap, client/components/contact-box/contact.js, client/components/contact-box/contact.test.js, client/components/footer/index.css, client/components/header/index.css, client/components/login/__snapshots__/login.test.js.snap, client/components/login/login.js, client/components/mobile-phone-change/__snapshots__/mobile-phone-change.test.js.snap, client/components/password-confirm/__snapshots__/password-confirm.test.js.snap, client/components/status/index.css, public/index.html
Improvements I'm doing while testing a few deployments.
=> [misc] Various minor improvements

client/components/login/login.js, client/components/login/login.test.js, client/components/status/status.js, client/utils/__mocks__/get-parameter-by-name.js, client/utils/get-parameter-by-name.js, client/utils/validate-token.js
If the app receives username and token as querystring parameters,
it will use these to perform token validation in the status component
and recognize the user.
This method is used by Social and SAML login.
Fixes #301
=> [fix] Fixed social login / SAML login #301

README.md, client/components/login/login.js, client/components/login/login.test.js, client/components/status/status.js, client/components/status/status.test.js
=> [feature] Implemented SAML logout

config/webpack.config.js
Changed webpack config to not to open browser
Closes #310
=> [change] Removed automatic opening of browser window on server start #310

.gitignore, client/actions/actions.test.js, client/actions/parse-organizations.js, client/actions/set-organization.js, client/components/404/404.test.js, client/components/contact-box/contact.test.js, client/components/footer/footer.test.js, client/components/header/header.test.js, client/components/login/login.test.js, client/components/mobile-phone-change/__snapshots__/mobile-phone-change.test.js.snap, client/components/modal/modal.test.js, client/components/organization-wrapper/index.js, client/components/organization-wrapper/organization-wrapper.js, client/components/organization-wrapper/organization-wrapper.test.js, client/components/password-change/password-change.test.js, client/components/password-confirm/password-confirm.test.js, client/components/password-reset/password-reset.test.js, client/components/payment-status/payment-status.test.js, client/index.js, client/test-config.json, client/utils/__mocks__/get-config.js, client/utils/get-config.js, config/setup.js
Used dynamic import of config files.
Closes #238
=> [change] Avoided loading config of all organizations #238

client/components/status/__snapshots__/status.test.js.snap, client/components/status/status.js, client/components/status/status.test.js
=> [change] Call getUserRadiusSession when userData is loaded #288

client/actions/actions.test.js, client/components/404/404.test.js, client/components/header/__snapshots__/header.test.js.snap, client/components/header/header.test.js, client/components/header/index.js, client/components/login/login.test.js, client/components/logout/index.js, client/components/logout/logout.test.js, client/components/mobile-phone-change/mobile-phone-change.test.js, client/components/mobile-phone-verification/mobile-phone-verification.test.js, client/components/modal/index.js, client/components/modal/modal.test.js, client/components/organization-wrapper/__snapshots__/organization-wrapper.test.js.snap, client/components/organization-wrapper/organization-wrapper.test.js, client/components/password-change/password-change.test.js, client/components/password-confirm/password-confirm.test.js, client/components/registration/registration.test.js, client/components/status/status.test.js, client/reducers/reducers.test.js, client/utils/utils.test.js, client/utils/validate-token.js
=> [tests] Increase test coverage

client/components/modal/__snapshots__/modal.test.js.snap, client/components/modal/index.css, client/components/modal/modal.js, client/components/status/__snapshots__/status.test.js.snap, client/components/status/index.css, client/components/status/status.js, client/index.css
Used logout modal CSS to for all other modals
Closes #322
=> [change] Made TOS and PP modal like logout modal #322

.github/workflows/ci.yml
Added saml in installing openwisp-radius
Closes #345
=> [ci] Fixed CI to install openwisp-radius #345

client/components/login/__snapshots__/login.test.js.snap, client/components/password-change/__snapshots__/password-change.test.js.snap, client/components/password-change/password-change.js, client/components/password-change/password-change.test.js, client/components/password-confirm/__snapshots__/password-confirm.test.js.snap, client/components/password-confirm/password-confirm.js, client/components/password-confirm/password-confirm.test.js, client/components/registration/__snapshots__/registration.test.js.snap, client/components/registration/registration.js, client/components/registration/registration.test.js, client/utils/password-toggle.js, client/utils/utils.test.js
Used another reference as second ref to toggle the fields and focus
on the selected one.
Closes #323
=> [ux] Improvements to reveal password feature #323

client/components/registration/registration.js, client/components/registration/registration.test.js, client/components/registration/subscriptions.test.js, client/constants/index.js, server/controllers/registration-controller.js, server/index.js, server/utils/proxy-urls.js
=> [change] Skip billing info for zero sum payments #336

.eslintrc.json, client/components/registration/registration.js, client/components/registration/registration.test.js, client/components/registration/subscriptions.test.js, client/components/registration/test-utils.js
Refactored subscriptions.test.js to use mount() so we can check
nexted components to be sure everything is under control.
I took the chance to introduce some minor improvements in
the Registration component.
=> [refactor] Registration: refactored tests + minor improvements

client/components/mobile-phone-verification/mobile-phone-verification.js, client/components/mobile-phone-verification/mobile-phone-verification.test.js
After verification updated userData username with new phone number
Fixes #353
=> [fix] Change username when phone number is changed and verified #353

README.md, client/components/footer/__snapshots__/footer.test.js.snap, client/components/header/__snapshots__/header.test.js.snap, client/components/header/header.js, client/components/header/header.test.js, client/components/header/index.css, client/utils/get-html.js
Added custom html support for sticky message
Closes #347
=> [feature] Added sticky message #347

client/components/login/login.js, client/components/mobile-phone-change/mobile-phone-change.js, client/components/mobile-phone-verification/mobile-phone-verification.js, client/components/password-change/password-change.js, client/components/password-confirm/password-confirm.js, client/components/password-reset/password-reset.js, client/components/registration/registration.js, client/utils/get-error-field.js, client/utils/get-error.js
Added get-error-field to remove repeated code.
Closes #357
=> [change] Reusable fuction for errors #357

client/components/login/login.js, client/components/mobile-phone-change/__snapshots__/mobile-phone-change.test.js.snap, client/components/mobile-phone-change/index.js, client/components/mobile-phone-change/mobile-phone-change.js, client/components/mobile-phone-change/mobile-phone-change.test.js, client/components/mobile-phone-verification/index.js, client/components/mobile-phone-verification/mobile-phone-verification.js, client/components/mobile-phone-verification/mobile-phone-verification.test.js, client/components/modal/modal.js, client/components/password-change/index.js, client/components/password-change/password-change.js, client/components/password-change/password-change.test.js, client/components/password-confirm/password-confirm.js, client/components/password-reset/index.js, client/components/password-reset/password-reset.js, client/components/password-reset/password-reset.test.js, client/components/registration/registration.js, client/components/registration/registration.test.js, client/utils/get-language-headers.js, server/controllers/mobile-phone-number-change-controller.js, server/controllers/mobile-phone-token-controller.js, server/controllers/obtain-token-controller.js, server/controllers/password-change-controller.js, server/controllers/password-reset-confirm-controller.js, server/controllers/password-reset-controller.js, server/controllers/plans-controller.js, server/controllers/registration-controller.js, server/controllers/user-radius-sessions-controller.js, server/controllers/validate-token-controller.js
Added selected language in accept-language header while calling OpenWISP RADIUS API.
Fixes #359
=> [fix] Added selected language in language headers while calling API #359

browser-test/language-change.test.js, browser-test/login.test.js, browser-test/mobile-phone-change.test.js, browser-test/mobile-verfication.test.js, browser-test/password-change.test.js, browser-test/password-confirm.test.js, browser-test/password-reset.test.js, browser-test/registration.test.js, browser-test/utils.js
- centralized tear down logic in one function
- always clear sessionStorage and localStorage
- ALWAYS call tearDown
Related to #379
=> [tests] Added tearDown function to browser tests #379

client/components/mobile-phone-verification/mobile-phone-verification.js, client/components/mobile-phone-verification/mobile-phone-verification.test.js, client/utils/handle-logout.js
Used optional parameter showLogoutToast in handleLogout function.
Fixes #375
=> [fix] Logout success toast when logging out from verification page #375

client/components/modal/index.css, client/components/modal/modal.js
Added loader while fetching modal content.
Fixes #374
=> [fix] Used default loader while loading PP or T&C #374

client/components/footer/footer.js, client/components/header/header.js
Added check for undefined link url
Closes #169
=> [bug] Fixed unique key props error when no links #169

browser-test/mobile-phone-change.test.js, browser-test/mobile-verfication.test.js, browser-test/password-change.test.js, browser-test/utils.js
Minor fixes to make test faster and robust.
Closes #379
=> [change] Fixed flaky browser tests #379

README.md, client/components/organization-wrapper/organization-wrapper.js, client/components/organization-wrapper/organization-wrapper.test.js, internals/config/default.yml, internals/generators/organization/config.yml.hbs, organizations/default/default.yml
List of CSS file can be added in the config.
Updated comments inside the config file.
Closes #372
=> [feature] Added support for multiple CSS files #372

client/components/status/status.js, client/components/status/status.test.js
Fixed user logged out when temporary connection issues.
Fixes #394
=> [fix] Logout only when unauthorized or forbidden while fetching sessions #394

client/components/login/login.js, client/components/login/login.test.js, client/components/organization-wrapper/__snapshots__/organization-wrapper.test.js.snap, client/components/organization-wrapper/organization-wrapper.js, client/components/organization-wrapper/organization-wrapper.test.js, client/components/payment-status/__snapshots__/payment-status.test.js.snap, client/components/payment-status/index.js, client/components/payment-status/payment-status.js, client/components/payment-status/payment-status.test.js, client/components/registration/registration.js, client/components/registration/subscriptions.test.js, client/index.css, client/utils/redirect-to-payment.js, client/utils/utils.test.js, i18n/de.po, i18n/en.po, i18n/fur.po, i18n/it.po, i18n/sl.po
Explain the payment (or credit/debit card verification) process
Before logging in the user to the captive portal and send them
to the payment gateway.
Since the user will have limited time to complete the transaction
to avoid abuses (since they basically get free internet for a few
minutes), we have to explain them what to do in case the timeout
is reached.
=> [feature] Added pre-payment page

browser-test/language-change.test.js, client/components/organization-wrapper/organization-wrapper.js, client/components/payment-status/payment-status.test.js, client/index.css, client/test-translation.json, client/utils/handle-logout.js, i18n/de.po, i18n/en.po, i18n/fur.po, i18n/it.po, i18n/ru.po, i18n/sl.po
Updated translations + minor issues found during testing.
=> [misc] Updated translations + minor issues found during testing

client/actions/actions.test.js, client/components/login/login.js, client/components/login/login.test.js, client/components/logout/logout.js, client/components/logout/logout.test.js, client/components/mobile-phone-verification/mobile-phone-verification.js, client/components/mobile-phone-verification/mobile-phone-verification.test.js, client/components/payment-status/payment-status.js, client/components/payment-status/payment-status.test.js, client/components/registration/registration.js, client/components/registration/subscriptions.test.js, client/components/status/status.js, client/components/status/status.test.js, client/reducers/organization.js, client/reducers/reducers.test.js, client/utils/utils.test.js
Fixes cp login after registration on paid plans.
=> [fix] Fixed cp login after registration on paid plans

.github/workflows/ci.yml
Removed cloning of openwisp-radius
Cache python dependencies
Closes #407
=> [ci] Cache python dependencies to run openwisp-radius #407

client/components/status/status.js, client/components/status/status.test.js
Added this.intervalId and fixed related tests.
Closes #406
=> [refactor] Removed intervalId from state in status component #406

client/components/organization-wrapper/organization-wrapper.js, client/components/organization-wrapper/organization-wrapper.test.js, client/components/registration/registration.js, client/components/registration/registration.test.js, client/components/registration/subscriptions.test.js
Passed loading state to registration page and call setLoading when
loading state changes in organization wrapper.
Fixes #421
=> [fix] Fixed race condition when setLoading is called #421

README.md, client/components/status/__snapshots__/status.test.js.snap, client/components/status/status.js, client/components/status/status.test.js
=> [feature] Added concept of public mode #399

config/setup.js
Added a customizer to merge array.
Fixes #424
=> [fix] Merge array with source object array value in variants config #424

client/components/logout/__snapshots__/logout.test.js.snap, client/components/organization-wrapper/__snapshots__/organization-wrapper.test.js.snap, client/components/payment-status/__snapshots__/payment-status.test.js.snap, client/components/registration/__snapshots__/registration.test.js.snap, client/components/registration/index.css, client/components/registration/registration.js, client/components/registration/registration.test.js, client/components/status/__snapshots__/status.test.js.snap, client/components/status/index.css, client/components/status/status.js, client/components/status/status.test.js, client/test-translation.json, client/utils/modal.css, client/utils/modal.js, i18n/en.po
Showing a modal if user is already registered with other organizations.
If user clicks yes then it gets redirected to login.
Closes #419
=> [feature] User can signup to multiple organizations #419

README.md
=> [docs] added ansible-role link

.github/workflows/ci.yml, browser-test/password-change.test.js, client/components/password-change/__snapshots__/password-change.test.js.snap, client/components/password-change/password-change.js, client/components/password-change/password-change.test.js, client/test-translation.json, i18n/en.po, server/controllers/password-change-controller.js, server/controllers/plans-controller.js
Added support for the current password field.
Closes #366
=> [change] Improved change password component to include old pwd field #366

client/components/modal/modal.js, client/components/modal/modal.test.js
=> [chores:ux] Hide main scrollbar when modals are open #459

client/components/mobile-phone-change/mobile-phone-change.js, client/components/mobile-phone-change/mobile-phone-change.test.js, client/components/mobile-phone-verification/mobile-phone-verification.js, client/components/password-change/password-change.js, client/components/password-change/password-change.test.js, client/components/payment-status/index.js, client/components/payment-status/payment-status.js, client/components/status/status.js, client/utils/utils.test.js, client/utils/validate-token.js
=> [change] Send user preferred language in validate token #476

client/components/mobile-phone-change/mobile-phone-change.js, client/components/mobile-phone-verification/mobile-phone-verification.js, client/components/password-change/password-change.js, client/components/payment-process/payment-process.js, client/components/status/status.js, client/utils/get-payment-status.js, server/controllers/mobile-phone-number-change-controller.js, server/controllers/mobile-phone-token-controller.js, server/controllers/password-change-controller.js, server/controllers/payments-controller.js, server/controllers/user-radius-sessions-controller.js, server/routes/account.js, server/routes/modal.js, server/routes/payment.js, server/routes/plans.js, server/utils/error-handler.js
=> [fix] Registration fix on mini-browsers which do not have cookies #487

client/components/login/login.js, client/components/login/login.test.js, client/components/organization-wrapper/organization-wrapper.test.js, internals/config/default.yml, server/controllers/obtain-token-controller.js, server/controllers/registration-controller.js, server/utils/send-cookies.js
=> [feature] Added support for django-sesame links #478

server/controllers/mobile-phone-token-controller.js, server/controllers/payments-controller.js
The controller was not using "getSlug" function to get organization
slug from configuration. This was causing issues with variants
of the organization.
=> [fix] Fixed mobile phone token verification URL

server/utils/send-cookies.js
=> [change] Use secure cookies when in production #515

browser-test/password-reset.test.js, client/components/password-reset/__snapshots__/password-reset.test.js.snap, client/components/password-reset/password-reset.js, client/components/password-reset/password-reset.test.js, client/test-translation.json, i18n/de.po, i18n/en.po, i18n/fur.po, i18n/it.po, i18n/ru.po, i18n/sl.po, internals/config/default.yml, internals/generators/organization/config.yml.hbs, server/controllers/password-reset-controller.js
=> [change] Allow username and phone number in password reset

README.md
=> [change] Updated node version to 16x in readme #530

client/components/registration/registration.js, client/components/registration/registration.test.js
=> [Fix] Show 404 if organization is not present #516

server/controllers/mobile-phone-number-change-controller.js, server/controllers/mobile-phone-token-controller.js, server/controllers/obtain-token-controller.js, server/controllers/password-change-controller.js, server/controllers/password-reset-confirm-controller.js, server/controllers/password-reset-controller.js, server/controllers/payments-controller.js, server/controllers/plans-controller.js, server/controllers/registration-controller.js, server/controllers/user-radius-sessions-controller.js, server/controllers/validate-token-controller.js, server/utils/logger.js
=> [change] Do no generate exception on 400 bad request #536

client/components/login/login.js, client/components/mobile-phone-change/mobile-phone-change.js, client/components/organization-wrapper/lazy-import.js, client/components/registration/registration.js, client/utils/get-config.js, client/utils/load-translation.js
=> [change] Rename chunks of build #538

server/controllers/mobile-phone-number-change-controller.js, server/controllers/mobile-phone-token-controller.js, server/controllers/obtain-token-controller.js, server/controllers/password-change-controller.js, server/controllers/password-reset-confirm-controller.js, server/controllers/password-reset-controller.js, server/controllers/payments-controller.js, server/controllers/plans-controller.js, server/controllers/registration-controller.js, server/controllers/user-radius-sessions-controller.js, server/controllers/validate-token-controller.js, server/utils/logger.js
=> [change] Removed Logger.error from controller files #540 

client/components/login/__snapshots__/login.test.js.snap, client/components/login/login.js, yarn.lock
=> [fix] Show only email label in default org login form #589

browser-test/mobile-verfication.test.js, browser-test/registration.test.js, client/components/registration/registration.js, client/components/registration/registration.test.js
=> [Fix] Fixed captive portal login after registration #605

client/components/payment-status/payment-status.js, client/components/payment-status/payment-status.test.js, client/components/status/status.js, client/components/status/status.test.js
=> [fix] Fixed payment flow redirect loop when payment requires internet #629

.github/workflows/ci.yml, client/components/mobile-phone-verification/__snapshots__/mobile-phone-verification.test.js.snap, client/components/mobile-phone-verification/mobile-phone-verification.js, client/components/mobile-phone-verification/mobile-phone-verification.test.js, client/index.css, client/test-translation.json, i18n/de.po, i18n/en.po, i18n/fur.po, i18n/it.po, i18n/ru.po, i18n/sl.po, organizations/default/client_assets/index.css, package.json, yarn.lock
=> [feature] Limit consecutive SMS sending #683

.github/workflows/ci.yml, package.json
Added this option in package.json to
facilitate development and testing.
=> [tests] Added NODE_OPTIONS=--openssl-legacy-provider

README.md
=> [change] Clarified captive_portal_login_form and captive_portal_logout_form #782

README.md, client/components/status/status.js
=> [docs] Improved captive portal settings docs

.github/workflows/ci.yml
=> [ci] Run on ubuntu-latest

client/components/status/status.js, client/components/status/status.test.js
=> [fix] Don't show "limit-info" div if API does not return any check #819

config/__tests__/add-org.test.js, config/add-org.js
=> [test] Added test for add-org command #808

client/actions/logout.js, client/components/status/index.js, client/components/status/status.js, client/components/status/status.test.js, docs/user/settings.rst, internals/config/default.yml, organizations/default/default.yml
=> [feature] Allowed synchronous captive portal authentication #864

browser-test/clear_data.py, browser-test/get_phone_token.py, browser-test/initialize_data.py, requirements-qa.txt
Switched python code to double quotes.
=> [qa] Switched python code to double quotes

client/components/status/__snapshots__/status.test.js.snap, client/components/status/status.js, client/components/status/status.test.js
Bug:
The upgrade button and limit exceeded message were shown only when the user was on the default plan.
Fix:
Both of the elements are shown whe the RADIUS limit is exceeded by the user.
=> [fix] Fixed upgrade button and limit exceeded message not rendering

i18n/de.po, i18n/en.po, i18n/es.po, i18n/fur.po, i18n/it.po, i18n/ru.po, i18n/sl.po
=> [chores:i18n] Updated translations

client/actions/logout.js, client/components/organization-wrapper/organization-wrapper.js, client/components/status/status.js, client/components/status/status.test.js
=> [fix] Relay querystring in sync auth mode #904

client/components/status/__snapshots__/status.test.js.snap, client/components/status/index.css, client/components/status/status.js, client/components/status/status.test.js, package.json, yarn.lock
- N/A I have updated the documentation.
=> [change] Made warning message customizable
