openwisp/openwisp-wifi-login-pages

package-lock.json

`npm install` showed me 7 errors out of which `npm audit fix` fixed 5, but the other still need attention as they might be breaking changes.
```
=== npm audit security report ===                        
SEMVER WARNING: Recommended action is a potentially breaking change
Critical        Cross-Site Scripting                                          
Package         dompurify                                                     
Dependency of   dompurify                                                     
Path            dompurify                                                     
More info       https://npmjs.com/advisories/1205                             
Critical        Cross-Site Scripting                                          
Package         dompurify …
```

Fix 5/7 vulnerabilities with npm audit fix

---

client/index.js
config/webpack.config.js

Added hot-module-replacement support. Described in [issue#33](https://github.com/openwisp/openwisp-wifi-login-pages/issues/33)

[config] Add hot-module-replacement to the webpack configuration

---

config/webpack.config.js
package.json
readme.md
server/index.js

Currently the webpack dev server and nodemon are running on a fixed
port.
This commit allows developers to choose their own port.
If no port was specified and the default one is already in use,
it will automatically find the next free port.
For information on how to set the ports, take a look at the readme.
This fixes #34

Allow custom ports #34

---

client/components/login/__snapshots__/login.test.js.snap
client/components/login/login.js
client/components/login/login.test.js
client/components/password-confirm/password-confirm.js
client/components/password-reset/__snapshots__/password-reset.test.js.snap
client/components/password-reset/password-reset.js
client/components/registration/__snapshots__/registration.test.js.snap
client/components/registration/registration.js
client/components/registration/registration.test.js
org-configurations/default-configuration.yml

This is a PR for commit which switches `openwisp-wifi-login-pages` from username to email in sign-up and login by using email instead of username on frontend side of the application and sending email to server as a value of `username` (so it doesn't change backend part).
***
- Updated `login.js` :
- Switched from username `input_field` to email `input_field`
- Changed state (now it works with `email` & `password`)
- Updated `registration.js` :
- Changed state (now it works with `email`, `password1` and `password2`)
- Removed username `input_field`
- Updated `default-configuration.yml`:
- Switched from `username` to `email` in `input_field`  of `login_form`
- Updated tests (`login.test.js` and `registration.test.js`)
- Updated snapshots (`login.test.js.snap` and …

[Enchancement] Switch from username to email in sign-up and login #41

---

readme.md

This is PR for commit which adds `david-dm` dependency and devDependency badge in `readme.md` instead of `Libraries.io` badge (due to `Libraries.io` rendering issue).
Fixes #42

[Dependency] Fix badge #42

---

readme.md

Ran tests on node versions 10.x.x & 11.x.x, either tests were failing or warnings were there. 
Worked fine for v12.0.0 or above
Closes #78

[doc] Added minimum node & npm version required#78

---

client/components/status/status.js

Problem was key was being set to inner link it should be on outer div so when multiple renders occur react will know the key is same or not or it has to render element or not.
@niteshsinha17 Please review this PR.

[fix] Fixes unique key props error

---

README.md
config/webpack.config.js
package.json

Now webpack analyzer can be avoided during the standard build process and yarn start
Fixes #223

[Fix] Separated webpack analyzer plugin from main plugins #223

---

browser-test/clear_data.py
browser-test/initialize_data.py
browser-test/login.test.js
client/components/login/login.js
client/components/status/status.js
client/components/status/status.test.js

Wait until captive portal login response to perform actions like:
- clearing the loading overlay
- redirecting the user to payment flow
- loading user sessions
Fixes #265

[change/fix] Wait until captive portal login response #265

---

.github/workflows/ci.yml

~~Refactor CI file~~ Changed order of build steps to run headless jasmine tests before running the browser based tests installing external dependencies to reduce CI time if tests fail.
Closes #316

[ci] Used yarn test before installing openwisp-radius #316

---

client/components/organization-wrapper/organization-wrapper.js
client/components/organization-wrapper/organization-wrapper.test.js

Added a check for prevProps.language must not be empty strings.
Force re-render of child components to update translations.
Fixes #350

[Fix] Browserlang selection bug fixed #350

---

client/components/mobile-phone-change/mobile-phone-change.test.js
client/components/mobile-phone-verification/mobile-phone-verification.js
client/components/mobile-phone-verification/mobile-phone-verification.test.js
client/components/organization-wrapper/organization-wrapper.test.js
client/components/password-change/index.js
client/components/password-change/password-change.js
client/components/password-change/password-change.test.js
client/components/payment-status/payment-status.js
client/components/payment-status/payment-status.test.js
client/components/status/status.js
client/components/status/status.test.js
client/utils/handle-logout.js
client/utils/utils.test.js
client/utils/validate-token.js

If the session is active then setUserData is not called after captive
portal logout. Added setUserData with initialData.userData after
performing captive portal logout.
Fixes #343
Closes #306

[fix] Added setUserData to called after logout #343

---

README.md
client/components/header/header.js
client/components/header/header.test.js
client/components/mobile-phone-change/mobile-phone-change.js
client/components/mobile-phone-change/mobile-phone-change.test.js
client/components/password-change/password-change.js
client/components/password-change/password-change.test.js
client/utils/should-link-be-shown.js
client/utils/utils.test.js
internals/generators/organization/config.yml.hbs
organizations/default.yml

Disabled password-change Component for social login and SAML.
Disabled phone-number change for method other than mobile_phone.
Support for methods and methods_excluded for links.
Closes #338
Closes #339 
Closes #368

[misc] Disable components for unrelated registration methods, add ways to avoid showing links to specific methods, changed "method" to "methods_only"

---

client/components/registration/registration.js
client/components/registration/subscriptions.test.js

The phone number shall be used when mobile verification is enabled
and the selected plan does not require a payment.
If the plan requires payment the stripped version of the email
is used instead.
This behavior was broken in previous changes.
@pandafy this fixes that issue I told you about.

[fix] Fixed username/phone number when plans are used

---

client/components/registration/__snapshots__/registration.test.js.snap
client/components/registration/registration.js
client/components/registration/registration.test.js

If the CSS class is assigned to the fallback suspense element, the difference with PhoneInput is not noticeable and this should be good enough.
Fixes #373

[fix] Fixed PhoneInput loading glitch #373

---

client/components/modal/index.css
client/components/modal/modal.js
client/components/organization-wrapper/index.css
client/components/organization-wrapper/organization-wrapper.js
client/components/organization-wrapper/organization-wrapper.test.js
client/components/status/__snapshots__/status.test.js.snap
client/components/status/index.css
client/components/status/status.js
client/index.css
client/utils/loader.js
client/utils/utils.test.js
public/index.html

- [change] Removed <title> contents
It makes more sense to leave this empty because it
will be loaded at runtime.
- [change] Centralized loading indicator HTML & CSS
We must avoid to redefine the HTML and CSS of the loading indicator
in mutliple places.
This logic was defined in:  
- index.html
- status
- organization wrapper
- model
Now the HTML is defined in the <Loader> component, while the CSS
is defined in the main <style> tag.
- [chores] Removed untranslated not found <title>

[misc] Simplified loader styles and other minor aspects

---

browser-test/mobile-phone-change.test.js
browser-test/mobile-verfication.test.js
browser-test/utils.js
client/actions/actions.test.js
client/components/login/login.js
client/components/organization-wrapper/lazy-import.js
client/components/organization-wrapper/organization-wrapper.js
client/components/organization-wrapper/organization-wrapper.test.js
client/components/status/status.js
client/components/status/status.test.js
client/reducers/organization.js
client/reducers/reducers.test.js
client/utils/utils.test.js
i18n/de.po
i18n/en.po
i18n/fur.po
i18n/it.po
i18n/ru.po
i18n/sl.po

After captive portal logout on PfSense, any outgoing HTTP request fails
for a few seconds.
For this reason we should avoid to lazily import Login, which can
get downloaded again and cause the logout process to hang.
Moreover, for the reasons above, during credit/debit card
payment/verification we cannot automatically log out and log in
the user, therefore we shall force a logout and ask the user
to log in after successful registration and payment.
Some informational toast messages with long autoClose have been
added to deal with the cases in which the wait time may last
for many seconds.
Closes #410

[fix/change] Fixed hanging logout + force logout after payment #410

---

client/components/status/status.js
client/components/status/status.test.js

Changed the concat code when page is 1 because due to internal state change it may
be possible that sessions will be fetched again for same page.
Fixes #420

[fix] Fixed children with same key error when past sessions load #420

---

README.md
config/setup.js

If slug is different from the parent configuration then creating a new organization
with different slug during setup.
Closes #429

[change] Added support for creating organization from variants #429

---

client/components/status/status.js
client/components/status/status.test.js

Status page will redirect to the draft payment page
(/<org-slug>/payment/draft) instead of payment process page.
Users should be always greeted by  payment instructions before
continuing with the payment.
Closes #494

[fix] Fixed "bank_card" redirects from status page #494

---

client/components/status/__snapshots__/status.test.js.snap
client/components/status/index.css
client/components/status/status.js

- break long emails and avoid layout break
- position session list at top of its box

[fix] Fixed status CSS quirks

---

client/components/mobile-phone-verification/mobile-phone-verification.js
client/components/mobile-phone-verification/mobile-phone-verification.test.js
client/constants/index.js
server/controllers/mobile-phone-token-controller.js
server/routes/account.js
server/utils/openwisp-urls.js

[change] Do not send new SMS unless needed #656

---

client/utils/get-payment-status.js
client/utils/utils.test.js

The `getPaymentStatus` would use toast.error if the response included  "error" payment status. It would use toast.info otherwise.

[change] Select toast level based on payment status

---

CHANGES.md
package.json

1.1.0 release
Signed-off-by: Gagan Deep <pandafy.dev@gmail.com>

1.1.0 release

---

.github/workflows/ci.yml

Get rid of CACHE_VERSION secret which has to be managed manually.
Let's use the OpenWISP RADIUS commit hash instead.
- N/A I have manually tested the changes proposed in this pull request.
- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
- N/A I have updated the documentation.
Closes #849.

[ci] Cache python env: use OpenWISP RADIUS commit hash #849

---

client/components/registration/__snapshots__/registration.test.js.snap
client/components/status/__snapshots__/status.test.js.snap
client/components/status/index.css
client/components/status/status.js
client/utils/modal.js

Allow making modal scrollable and enable this behavior in the plans modal, works as in the gif below.

[fix] Make plans modal in status scrollable
